from models.common import StateTemplate

STATE_TEMPLATES: list[StateTemplate] = [
    StateTemplate(
        id="idle",
        name="Idle",
        category="core",
        baseType="idle",
        prompt="idle stance, at rest, readable silhouette, looping idle pose",
        directionsMode="8",
        frameCount=1,
        loop=True,
        animationSpeed=6,
        kind="static",
    ),
    StateTemplate(
        id="walk",
        name="Walk",
        category="core",
        baseType="walk",
        prompt="walk cycle key pose, mid-stride, clear contact and passing positions",
        directionsMode="8",
        frameCount=4,
        loop=True,
        animationSpeed=8,
        kind="animated",
    ),
    StateTemplate(
        id="sitting",
        name="Sitting",
        category="core",
        baseType="sitting",
        prompt="sitting pose, grounded, calm, full body readable from the chosen camera",
        directionsMode="4",
        frameCount=1,
        loop=True,
        animationSpeed=4,
        kind="static",
    ),
    StateTemplate(
        id="talking",
        name="Talking",
        category="core",
        baseType="talking",
        prompt="talking pose, mouth slightly open, attentive, conversational body language",
        directionsMode="4",
        frameCount=2,
        loop=True,
        animationSpeed=6,
        kind="animated",
    ),
    StateTemplate(
        id="laughing",
        name="Laughing",
        category="social",
        baseType="laughing",
        prompt="laughing pose, character-specific laughter, not a generic cartoon laugh",
        directionsMode="4",
        frameCount=2,
        loop=True,
        animationSpeed=7,
        kind="animated",
    ),
    StateTemplate(
        id="waving",
        name="Waving",
        category="social",
        baseType="waving",
        prompt="waving one hand, greeting, the rest of the body stays in character",
        directionsMode="4",
        frameCount=2,
        loop=True,
        animationSpeed=7,
        kind="animated",
    ),
    StateTemplate(
        id="thinking",
        name="Thinking",
        category="social",
        baseType="thinking",
        prompt="thinking pose, inward focus, slight head tilt or hand near chin if it fits the character",
        directionsMode="1",
        frameCount=1,
        loop=True,
        animationSpeed=4,
        kind="static",
    ),
    StateTemplate(
        id="surprised",
        name="Surprised",
        category="social",
        baseType="surprised",
        prompt="surprised reaction, still the same character, no slapstick exaggeration unless the emotion profile asks for it",
        directionsMode="4",
        frameCount=1,
        loop=False,
        animationSpeed=6,
        kind="static",
    ),
    StateTemplate(
        id="happy",
        name="Happy",
        category="emotional",
        baseType="happy",
        prompt="happy resting expression and posture, true to the character's facial range",
        directionsMode="4",
        frameCount=1,
        loop=True,
        animationSpeed=4,
        kind="static",
    ),
    StateTemplate(
        id="sad",
        name="Sad",
        category="emotional",
        baseType="sad",
        prompt="sad pose and expression, grief held in the body according to the emotion profile",
        directionsMode="4",
        frameCount=1,
        loop=True,
        animationSpeed=4,
        kind="static",
    ),
    StateTemplate(
        id="angry",
        name="Angry",
        category="emotional",
        baseType="angry",
        prompt="angry pose, tension in the face and shoulders matching the character's anger style",
        directionsMode="4",
        frameCount=1,
        loop=True,
        animationSpeed=5,
        kind="static",
    ),
    StateTemplate(
        id="worried",
        name="Worried",
        category="emotional",
        baseType="worried",
        prompt="worried, uneasy, protective concern rather than panic unless the profile is highly expressive",
        directionsMode="4",
        frameCount=1,
        loop=True,
        animationSpeed=4,
        kind="static",
    ),
    StateTemplate(
        id="floatingIdle",
        name="Floating Idle",
        category="spirit",
        baseType="floatingIdle",
        prompt="hovering idle, spectral lower body drifting, no grounded feet, slow float",
        directionsMode="8",
        frameCount=2,
        loop=True,
        animationSpeed=5,
        kind="animated",
    ),
    StateTemplate(
        id="materialize",
        name="Materialize",
        category="spirit",
        baseType="materialize",
        prompt="spirit body coalescing from pale mist, still recognizable as the same character",
        directionsMode="1",
        frameCount=4,
        loop=False,
        animationSpeed=8,
        kind="animated",
    ),
    StateTemplate(
        id="fadeOut",
        name="Fade Out",
        category="spirit",
        baseType="fadeOut",
        prompt="spirit body dissolving into mist, silhouette breaking into pale particles",
        directionsMode="1",
        frameCount=4,
        loop=False,
        animationSpeed=8,
        kind="animated",
    ),
    StateTemplate(
        id="memoryEcho",
        name="Memory Echo",
        category="spirit",
        baseType="memoryEcho",
        prompt="faint memory-echo pose, more translucent, distant, same identity, quieter presence",
        directionsMode="4",
        frameCount=1,
        loop=True,
        animationSpeed=3,
        kind="static",
    ),
]


def template_by_id(template_id: str) -> StateTemplate | None:
    return next((t for t in STATE_TEMPLATES if t.id == template_id), None)
